### ISSUE TITLE
Integrate a form submitted and sms

### ISSUE THREAD

**Issue by tapaswenipathak** [tapaswenipathak/API-list#2]
Given a form, after submit you should get a sms. You can use Twilio API.

**Comment by singalhimanshu** [comment]
What fields should the form have? And we have to send a mail or a sms on mobile number?

**Comment by tapaswenipathak** [comment]
On Mon, May 13, 2019 at 4:38 PM Himanshu <notifications@github.com> wrote:
>
> What fields should the form have? And we have to send a mail or a sms on mobile number?

You should create a form, any sample form, on click of submit the user
should get an sms.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub, or mute the thread.



-- 
Tapasweni

**Comment by singalhimanshu** [comment]
> 
> On Mon, May 13, 2019 at 4:38 PM Himanshu ***@***.***> wrote: What fields should the form have? And we have to send a mail or a sms on mobile number?
> You should create a form, any sample form, on click of submit the user should get an sms.
> […](#)
> — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or mute the thread.
> -- Tapasweni

The data should be saved in the database?

**Comment by tapaswenipathak** [comment]
On Mon, May 13, 2019 at 6:38 PM Himanshu <notifications@github.com> wrote:
>
> On Mon, May 13, 2019 at 4:38 PM Himanshu @.***> wrote: What fields should the form have? And we have to send a mail or a sms on mobile number?
> You should create a form, any sample form, on click of submit the user should get an sms.
> …
> — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or mute the thread.
> -- Tapasweni
>
> The data should be saved in the database?

Ya in the sample you can do, I just need on click of submit button the
user should get an sms.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub, or mute the thread.



-- 
Tapasweni

**Comment by singalhimanshu** [comment]
Can I do just sms functionality for now and database later?

**Comment by tapaswenipathak** [comment]
On Mon, May 13, 2019 at 6:49 PM Himanshu <notifications@github.com> wrote:
>
> Can I do just sms functionality for now and database for later?

Sure, just make sure at least a text fields is added in the db when
the user clicks on submit.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub, or mute the thread.



-- 

Tapasweni

**Comment by singalhimanshu** [comment]
Okay I'm working on it
