### ISSUE TITLE
Implement Twilio API generic implementation

### ISSUE THREAD

**Issue by tapaswenipathak** [tapaswenipathak/API-list#6]
https://github.com/tapaswenipathak/API-list/blob/0274abbb9306114498109b75e0643942b2d89dd4/main/views.py#L19-L25

**Comment by singalhimanshu** [comment]
Generic Implementation meaning can you specify it more?

**Comment by tapaswenipathak** [comment]
On Mon, May 27, 2019 at 7:34 PM Himanshu <notifications@github.com> wrote:
>
> Generic Implementation meaning can you specify it more?

You have implemented only for +91 code. Generic would implement for
any extension number.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub, or mute the thread.



-- 
Tapasweni
